spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KingBlueSky/config-repo.git
          username: 469799409@qq.com
          password: jp80890912345
          basedir: D:/jbwang/idea18/spring/baseDir
  rabbitmq:
    host: 192.168.142.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"
  security:
    enabled: false
#server:
#  port: 8083